### PR TITLE
Fix popen_spawn when specifying a path on Windows which contains "\" …

### PR DESCRIPTION
**Pull request by eli-b**
…separators

### CODE REVIEW

**Comment by techalchemy** [comment]
As I mentioned on the referenced PR, it might be a better approach to use `posix=(os.name == 'posix')` when testing for posix compliance...

**Comment by eli-b** [comment]
I've updated the PR according to your suggestion.

**Comment by takluyver** [comment]
Which referenced PR are you discussing?

**Comment by eli-b** [comment]
I think @techalchemy meant [this PR](https://github.com/kennethreitz/pipenv/pull/564).

**Comment by takluyver** [comment]
Thanks, I should have seen that.

**Pull request merged**
