### PR TITLE
Naïve workaround of the bracketed-paste mode

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/pexpect/pexpect/issues/669

### CODE REVIEW

**Comment by hroncok** [comment]
Apparently, the replacement needs to happen "sooner" or differently:

I went through failed packages in your testing copr. Most of them have failures unrelated to this PR, but two of them seems like not being fixed. 

[pytest](https://download.copr.fedorainfracloud.org/results/churchyard/strip_bracketed_paste/fedora-rawhide-x86_64/01876166-pytest/builder-live.log.gz)
~~~~
_____________________ TestPDB.test_pdb_interaction_doctest _____________________

self = <test_debugging.TestPDB object at 0x7f03af0d5100>
testdir = <Testdir local('/tmp/pytest-of-mockbuild/pytest-0/test_pdb_interaction_doctest0')>

    def test_pdb_interaction_doctest(self, testdir):
        p1 = testdir.makepyfile(
            """
            def function_1():
                '''
                >>> i = 0
                >>> assert i == 1
                '''
        """
        )
        child = testdir.spawn_pytest("--doctest-modules --pdb %s" % p1)
        child.expect("Pdb")
    
        assert "UNEXPECTED EXCEPTION: AssertionError()" in child.before.decode("utf8")
    
        child.sendline("'i=%i.' % i")
        child.expect("Pdb")
>       assert "\r\n'i=0.'\r\n" in child.before.decode("utf8")
E       assert "\r\n'i=0.'\r\n" in ") 'i=%i.' % i\r\n\x1b[?2004l\r'i=0.'\r\n\x1b[?2004h("
E        +  where ") 'i=%i.' % i\r\n\x1b[?2004l\r'i=0.'\r\n\x1b[?2004h(" = <built-in method decode of bytes object at 0x7f03af0d4120>('utf8')
E        +    where <built-in method decode of bytes object at 0x7f03af0d4120> = b") 'i=%i.' % i\r\n\x1b[?2004l\r'i=0.'\r\n\x1b[?2004h(".decode
E        +      where b") 'i=%i.' % i\r\n\x1b[?2004l\r'i=0.'\r\n\x1b[?2004h(" = <pexpect.pty_spawn.spawn object at 0x7f03af0b0310>.before

~~~~

[python-metakernel](https://download.copr.fedorainfracloud.org/results/churchyard/strip_bracketed_paste/fedora-rawhide-x86_64/01876191-python-metakernel/builder-live.log.gz)
~~~~
_________________________ REPLWrapTestCase.test_python _________________________

self = <metakernel.tests.test_replwrap.REPLWrapTestCase testMethod=test_python>

    def test_python(self):
        if platform.python_implementation() == 'PyPy':
            raise unittest.SkipTest("This test fails on PyPy because of REPL differences")
    
        p = replwrap.python(sys.executable)
        res = p.run_command('4+7')
>       assert res.strip() == '11'
E       AssertionError: assert '\x1b[?2004l\...\n\x1b[?2004h' == '11'
E         - 11
E         + [?2004l
E         + 11
E         + [?2004h

/builddir/build/BUILD/metakernel-0.27.5/metakernel/tests/test_replwrap.py:81: AssertionError
~~~~

**Comment by Red-M** [comment]
Automatically stripping data is not a good idea, if this was for testing reasons, please run the tests locally.

**Comment by hroncok** [comment]
>  if this was for testing reasons, please run the tests locally.

No, I actually genuinely tried to help. Sorry about that.

**Comment by Red-M** [comment]
Apologies, there was 2 of these PRs trying to do similar things both as drafts.

**Pull request closed without merging**
