### PR TITLE
Add preexec_fn to PopenSpawn

### PR DESCRIPTION
**Pull request by tcwalther**
This PR adds the keyword argument `preexec_fn` to `PopenSpawn`, so that it can be passed to the `subprocess.Popen` call.

### CODE REVIEW

**Comment by takluyver** [comment]
Makes sense, thanks!

**Comment by tcwalther** [comment]
Thanks so much for merging. Do you think it would be possible to push a new version 4.3.2 with this functionality to PyPI?

**Comment by takluyver** [comment]
I'm trying to get around to reviewing #464 - I'll get a new release out once that's sorted. I'm busy with family matters for the next couple of days, though.

**Comment by tcwalther** [comment]
That sounds great, thank you very much!

**Comment by ryanpetrello** [comment]
@takluyver I'll add my 👍 to the hat on a new PyPI release whenever you have spare time 😄 

Thank you very much!

**Pull request merged**
