### PR TITLE
Release notes and version number update for 4.8.0

### PR DESCRIPTION
**Pull request by dluyer**

### CODE REVIEW

**Comment by dluyer** [comment]
Please review, and comment if you have anything outstanding which we should hold off the release for.

**Comment by dluyer** [comment]
Release is also drafted once this is merged.

**Comment by takluyver** [comment]
Thanks @dluyer, this looks good to me. Do you want to let me know your PyPI username, and I'll add you on there so you can publish the package?

**Comment by dluyer** [comment]
Sure, PyPI username 'luyer'.  Thanks!

**Comment by takluyver** [comment]
Great, you should have access to it now.

**Comment by dluyer** [comment]
OK, this is now released on github and PyPI.

https://pexpect.readthedocs.io/en/stable/ has the old version number; I'll look into that.

**Comment by dluyer** [comment]
... that has the new version number now, too.  Perhaps it was just a propagation delay.

**Comment by takluyver** [comment]
:+1: 

I think RTD is quite eagerly cached - I often find that Ctrl-F5 reveals changes I made recently.

**Pull request merged**
