### PR TITLE
Release notes for 4.6

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Comment by ryanpetrello** [comment]
screen shot 2018-05-24 at 6 43 18 am

**Comment by ryanpetrello** [comment]
Hold merging this until https://github.com/pexpect/pexpect/pull/490 is in.

**Comment by takluyver** [comment]
:+1:

**Comment by Red-M** [comment]
when I merge #490 I'll merge this in too, since thomas is ok with this.

**Comment by Red-M** [comment]
#490 is fine to merge now.

**Comment by takluyver** [comment]
I've put 4.6 up on PyPI.

**Pull request merged**
