### PR TITLE
Allow delaybeforesend=None to skip the sleep completely

### PR DESCRIPTION
**Pull request by jdemeyer**
Yet another micro-optimization.

### CODE REVIEW

**Comment by takluyver** [comment]
1. Is there actually any measurable benefit to avoiding the call of `time.sleep(0)`?
2. Why not just check `== 0` rather than introducing a special alternative value?

**Comment by jdemeyer** [comment]
> Is there actually any measurable benefit to avoiding the call of time.sleep(0)?

I haven't actually tested it. But I know from general experience that avoiding system calls is a good idea: they involve context switches between user-space and kernel-space. This takes a small but measurable amount of time.

> Why not just check == 0 rather than introducing a special alternative value?

I just did that for consistency with #291.

**Comment by jquast** [comment]
The purpose of a sleep call for 0 seconds would be to allow other threads to run,
https://github.com/python/cpython/blob/master/Modules/timemodule.c#L1431

**Comment by jquast** [comment]
I support this for merge, ok @takluyver?

The ``None`` type check, rather than a 0-second check is significant, and a value of 0 continues to release the thread (matches previous behavior that may be dependent)

**Comment by jdemeyer** [comment]
Tests added.

What does `needs-changelog` mean, what should I change?

**Comment by jquast** [comment]
> What does needs-changelog mean, what should I change?

We will probably do that for you, It is a reminder to to update doc/history.rst for a 4.1 release, to describe this new keyword argument behavior.

**Comment by takluyver** [comment]
Thanks, this looks fine to me. I don't especially like passing the gil-releasing decision on to users - it feels like a detail they shouldn't have to care about - but I guess that's the way things go with this type of code.

**Pull request merged**
