### PR TITLE
On hold: Creates a pxsshu variant for using Unicode strings in Python 3

### PR DESCRIPTION
**Pull request by wsong**

### CODE REVIEW

**Comment by jquast** [comment]
looks good -- @wsong I presume you tested this with some utf-8 or big-5 encoded server that, with pxssh, would raise UnicodeDecodeError?

What do you think @takluyver ? ok to merge by me (and add to changelog)

**Comment by wsong** [comment]
@jquast Actually, I wrote this because in Python 3, child.sendline('foobar') would error because 'foobar' is a string and not a bytes object.  See https://github.com/pexpect/pexpect/issues/169.

**Comment by jquast** [comment]
Yes, that is much related, and this would indeed fix it.

(note: tests.test_interact.InteractTestCase.test_interact_spawn_eof intermittently fails for different python versions on travis)

**Comment by takluyver** [comment]
Fine by me. Please do add a very brief [test](https://github.com/pexpect/pexpect/blob/master/tests/test_pxssh.py) and [doc mention](https://raw.githubusercontent.com/pexpect/pexpect/master/doc/api/pxssh.rst) for the new class.

**Comment by wsong** [comment]
I've added some docs and a test, but the README for running the test seems to be out of date; there is no testall.py tool.

Additionally, the "make docs" command fails with:

make: *** No rule to make target `doc/index.template.html', needed by `docs'.  Stop.

**Comment by takluyver** [comment]
Thanks. You can run the tests with `py.test` and build the docs with `cd doc && make html`. I'll update the README and Makefile.

**Comment by wsong** [comment]
I noticed that the test I added fails with this error in Python 2.7:

```
======================================== FAILURES ========================================
________________________ PxsshTestCase.test_fake_ssh_with_unicode ________________________

self = <tests.test_pxssh.PxsshTestCase testMethod=test_fake_ssh_with_unicode>

    def test_fake_ssh_with_unicode(self):
        ssh = pxssh.pxsshu()
>       ssh.login('server', 'me', password='s3cret')

test_pxssh.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../pexpect/pxssh.py:214: in login
    i = self.expect(["(?i)are you sure you want to continue connecting", original_prompt, "(?i)(?:password)|(?:passphrase for key)", "(?i)permission denied", "(?i)terminal type", TIMEOUT, "(?i)connection closed by remote host"], timeout=login_timeout)
../pexpect/spawnbase.py:277: in expect
    compiled_pattern_list = self.compile_pattern_list(pattern)
../pexpect/spawnbase.py:187: in compile_pattern_list
    self._pattern_type_err(p)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pexpect.pxssh.pxsshu object at 0x107c9de50>
pattern = '(?i)are you sure you want to continue connecting'

    def _pattern_type_err(self, pattern):
        raise TypeError('got {badtype} ({badobj!r}) as pattern, must be one'
                        ' of: {goodtypes}, pexpect.EOF, pexpect.TIMEOUT'\
                        .format(badtype=type(pattern),
                                badobj=pattern,
                                goodtypes=', '.join([str(ast)\
>                                   for ast in self.allowed_string_types])
                                )
                        )
E       TypeError: got <type 'str'> ('(?i)are you sure you want to continue connecting') as pattern, must be one of: <type 'unicode'>, pexpect.EOF, pexpect.TIMEOUT
```

Is there an established way in the pexpect codebase to get around this?

**Comment by takluyver** [comment]
One of the string literals - probably the password - needs to be a unicode literal, i.e. `u'secret'`. This is valid on Python 2 and Python 3.3 and above, which covers all the versions we support, so it's safe to use.

**Comment by wsong** [comment]
I'm still getting the same error; it seems that the .expect() calls in login don't work with str-type strings in Python 2.  Is this expected?  Why does SpawnBaseUnicode not have allowed_string_types = (str, unicode) instead of just (unicode,)?

**Comment by jquast** [comment]
> Why does SpawnBaseUnicode not have allowed_string_types = (str, unicode) instead of just (unicode,)?

The base pexpect.pxssh class needs to use like:
```python
self.expect([self.string_type("(?i)are you sure you want to continue connecting"),
             ...
```

which should be bytes or unicode depending on pxssh/pxsshu (and str/unicode/bytes depending on python version)

**Comment by takluyver** [comment]
That's expected, SpawnBaseUnicode is a strict unicode interface, so you need to expect unicode strings for it.

**Comment by wsong** [comment]
Unfortunately, that won't work in Python 3 because string_type is bytes, and bytes(<a string>) is invalid because you need to specify an encoding (e.g. "bytes('foobar', 'utf-8')").

**Comment by wsong** [comment]
So do we have an established way of building strings/bytes/unicode/whatever with a SpawnBase object?  Could we just provide a build_string() method or something that takes in a string and returns a str, unicode, or bytes object (in the latter case using the 'utf-8' encoding)?

**Comment by takluyver** [comment]
We're considering a different way to distinguish bytes vs unicode in issue #159.

**Pull request closed without merging**
