### PR TITLE
fix select func override select module

### PR DESCRIPTION
**Pull request by danielino**
There is a rare circumstance when select module is replaced or disturbed by select() function in pty_spawn.py

```
  File "/Users/****/****/venv/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 446, in select
    return poll_ignore_interrupts([self.child_fd], timeout)
  File "/Users/****/****/venv/lib/python3.7/site-packages/pexpect/utils.py", line 166, in poll_ignore_interrupts
    poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'

```

debugging  with breakpoint() in select.utils module

```
> /Users/****/*****/venv/lib/python3.7/site-packages/pexpect/utils.py(168)poll_ignore_interrupts()
-> poller = select.poll()
(Pdb) dir(select)
[ ### ....  A LOT OF  CONSTANT ...... ###, 'POLLWRNORM', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'error', 'select'] <-- some methods are missing from module.
````
replacing function in pty_spawn.py fix the issue.

```
(Pdb) dir(select)
[ ....... ', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'error', 'kevent', 'kqueue', 'poll', 'select']
```

Signed-off-by: Daniele Marcocci <daniele.marcocci@par-tec.it>

### CODE REVIEW

**Comment by takluyver** [comment]
That doesn't seem right. Defining a function inside another function wouldn't affect the namespace of a separate module (unless there's some horrible and unlikely bug in Python itself). And if the select function was replacing the select module somehow, the error message would say `'function' object has no attribute 'poll'` (instead of `module 'select'...`). It also doesn't have that set of attributes.

Sorry, but I think that the issue coincidentally went away at the same time you made the change, for some other reason.

There are some platforms where poll is not supported, according to the Python docs. I'm not sure which those are, but if you've got one, you'd presumably see the problem all the time.

**Comment by danielino** [comment]
i'm using osx, but poll is working well:

```
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import select                                                                                                                                                                                                                     

In [2]: select.poll()                                                                                                                                                                                                                     
Out[2]: <select.poll at 0x10764e2a0>

In [3]:  
```

this is the full stack trace 
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/danielino/AnsibleWorker/venv/lib/python3.7/site-packages/ansible_runner/runner.py", line 177, in run
    searchwindowsize=100)
  File "/Users/danielino/AnsibleWorker/venv/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/Users/danielino/AnsibleWorker/venv/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/danielino/AnsibleWorker/venv/lib/python3.7/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/Users/danielino/AnsibleWorker/venv/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 457, in read_nonblocking
    if myselect(0):
  File "/Users/danielino/AnsibleWorker/venv/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 446, in myselect
    return poll_ignore_interrupts([self.child_fd], timeout)
  File "/Users/danielino/AnsibleWorker/venv/lib/python3.7/site-packages/pexpect/utils.py", line 167, in poll_ignore_interrupts
    poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'

```

i try to restore the file and the issue go back.

**Comment by takluyver** [comment]
It looks like the select module has some... *interesting* code which runs on Macs, trying to detect a broken poll implementation. If it finds one, it deletes the poll attribute from the module:
https://github.com/python/cpython/blob/1dc1acbd73f05f14c974b7ce1041787d7abef31e/Modules/selectmodule.c#L2467-L2474

I can see from your paths that you're on Mac, so I suspect you're hitting some kind of race condition with this, so it occasionally decides that poll is broken and deletes it from the module. The apparent effect of changing code in pexpect might be random chance, or something (maybe bytecode compilation) may be affecting the race condition enough to make it more or less likely.

I have been [nerd sniped](https://www.xkcd.com/356/) :wink: .

**Comment by takluyver** [comment]
If you can boil it down to a minimal example which reproduces the issue, even if it has to be launched in a shell loop until it fails, please do open a Python issue at https://bugs.python.org/

**Pull request closed without merging**
