### PR TITLE
disable max canon tests, retain file contents

### LINKED ISSUE #276: test_max_no_icanon: AssertionError: TIMEOUT not raised
```
[brain@x1carbon pexpect]$ py.test-3 tests/test_maxcanon.py 
============================= test session starts ==============================
platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.3
rootdir: /home/brain/git/fedora/python-pexpect/pexpect, inifile: setup.cfg
collected 3 items 

tests/test_maxcanon.py .F.

=================================== FAILURES ===================================
_______________________ TestCaseCanon.test_max_no_icanon _______________________

self = <tests.test_maxcanon.TestCaseCanon testMethod=test_max_no_icanon>

    @pytest.mark.skipif(
        sys.platform.lower().startswith('freebsd'),
        reason='os.write to BLOCK indefinitely on FreeBSD in this case'
    )
    def test_max_no_icanon(self):
        " may exceed maximum input bytes if canonical mode is disabled. "
        # given,
        child = pexpect.spawn('bash', echo=self.echo, timeout=5)
        child.sendline('stty -icanon imaxbel')
        child.sendline('echo BEGIN; cat')
        send_bytes = self.max_input + 11
    
        # exercise,
        child.sendline('_' * send_bytes)
    
        # fast forward beyond 'cat' command, as ^G can be found as part of
        # set-xterm-title sequence of $PROMPT_COMMAND or $PS1.
        child.expect_exact('BEGIN')
    
        if os.environ.get('TRAVIS', None) == 'true':
            # Travis-CI has intermittent behavior here, possibly
            # because the master process is itself, a PTY?
            return
    
        # BEL is *not* found,
        with self.assertRaises(pexpect.TIMEOUT):
>           child.expect_exact('\a', timeout=1)
E           AssertionError: TIMEOUT not raised

tests/test_maxcanon.py:165: AssertionError
----------------------------- Captured stdout call -----------------------------

 tests.test_maxcanon.TestCaseCanon.test_max_no_icanon 
====================== 1 failed, 2 passed in 2.60 seconds ======================
```

### PR DESCRIPTION
**Pull request by jquast**
Closes #276 

- fix indentation of documentation, fixes '256' in example as code output, instead of paragraph output.
- delete tests/test_maxcanon.py: the boundry value of MAX_CANON should not be a test.
- 2 new tools: ``display-{fpathconf.maxcanon}.py``: ``tests/test_maxcanon.py`` has been deleted and turned int an "autodetection" tool of sorts, no longer attempting to assert exacting values, but determine it programmatically.

### CODE REVIEW

**Comment by takluyver** [comment]
Would it make sense to refactor this code and put it alongside our other diagnostic utilities in the tools folder?

**Comment by jquast** [comment]
ok, will re-propose

**Comment by jquast** [comment]
Ready for new review @takluyver 

tests have been turned into two new tools: ``display-{fpathconf.maxcanon}.py``.

**Comment by ignatenkobrain** [comment]
Looks like CI fails.

**Comment by jquast** [comment]
CI Passed fine I'm in-progress upgrading this volunteer build farm outside of travis, so the MacOS agent is raising a false error.

**Comment by jquast** [comment]
If you're looking to play with the branch, I would be interested in your output value of `` tools/display-maxcanon.py`` @ignatenkobrain :)

**Comment by ignatenkobrain** [comment]
```python
Exception AttributeError: "'spawn' object has no attribute 'closed'" in <bound method spawn.__del__ of <pexpect.spawn object at 0x7f4a15126b50>> ignored
Traceback (most recent call last):
  File "./tools/display-maxcanon.py", line 73, in <module>
    detect_maxcanon()
  File "./tools/display-maxcanon.py", line 38, in detect_maxcanon
    echo=True, encoding='utf8', timeout=3)
TypeError: __init__() got an unexpected keyword argument 'echo'
```

**Comment by jquast** [comment]
@ignatenkobrain that code is for pexpect 4.0, you are using pexpect version 3.2, which is why the code is incompatible, don't worry about it, no hassle.

**Comment by ignatenkobrain** [comment]
@jquast I'm using only 4.0, 4.0.1 tbh

**Comment by jquast** [comment]
@ignatenkobrain i don't disbelieve that you have the source code tree checked out.

But that error only reproduces with a very old version of pexpect, 3.2 to be exact. ``python -c 'import pexpect;print(pexpect.__file__)'`` will more than likely point to a system-wide installation of pexpect (pip freeze |grep pexect would be 3.2).

```
$ pip install pexpect==3.2
$ python ~/Code/pexpect/tools/display-maxcanon.py
Exception AttributeError: "'spawn' object has no attribute 'closed'" in <bound method spawn.__del__ of <pexpect.spawn object at 0x1040a7990>> ignored
Traceback (most recent call last):
  File "/Users/docker/Code/pexpect/tools/display-maxcanon.py", line 73, in <module>
    detect_maxcanon()
  File "/Users/docker/Code/pexpect/tools/display-maxcanon.py", line 38, in detect_maxcanon
    echo=True, encoding='utf8', timeout=3)
TypeError: __init__() got an unexpected keyword argument 'echo'

$ pip install --upgrade pexpect==3.3
$ python ~/Code/pexpect/tools/display-maxcanon.py
Exception AttributeError: "'spawn' object has no attribute 'closed'" in <bound method spawn.__del__ of <pexpect.spawn object at 0x101fd4a10>> ignored
Traceback (most recent call last):
  File "/Users/docker/Code/pexpect/tools/display-maxcanon.py", line 73, in <module>
    detect_maxcanon()
  File "/Users/docker/Code/pexpect/tools/display-maxcanon.py", line 38, in detect_maxcanon
    echo=True, encoding='utf8', timeout=3)
TypeError: __init__() got an unexpected keyword argument 'encoding'

$ pip install --upgrade pexpect>=4.0
$ python ~/Code/pexpect/tools/display-maxcanon.py
auto-detecting MAX_CANON: 1024
```

**Comment by ignatenkobrain** [comment]
```
+ /usr/bin/python2 ./tools/display-sighandlers.py
name       value description
---------------------------------
SIGABRT    6     default(SIG_DFL)
SIGALRM    14    default(SIG_DFL)
SIGBUS     7     default(SIG_DFL)
SIGCHLD    17    default(SIG_DFL)
SIGCLD     17    default(SIG_DFL)
SIGCONT    18    default(SIG_DFL)
SIGFPE     8     default(SIG_DFL)
SIGHUP     1     default(SIG_DFL)
SIGILL     4     default(SIG_DFL)
SIGINT     2     <built-in function default_int_handler>
SIGIO      29    default(SIG_DFL)
SIGIOT     6     default(SIG_DFL)
SIGKILL    9     default(SIG_DFL)
SIGPIPE    13    ignored(SIG_IGN)
SIGPOLL    29    default(SIG_DFL)
SIGPROF    27    default(SIG_DFL)
SIGPWR     30    default(SIG_DFL)
SIGQUIT    3     default(SIG_DFL)
SIGRTMAX   64    default(SIG_DFL)
SIGRTMIN   34    default(SIG_DFL)
SIGSEGV    11    default(SIG_DFL)
SIGSTOP    19    default(SIG_DFL)
SIGSYS     31    default(SIG_DFL)
SIGTERM    15    default(SIG_DFL)
SIGTRAP    5     default(SIG_DFL)
SIGTSTP    20    default(SIG_DFL)
SIGTTIN    21    default(SIG_DFL)
SIGTTOU    22    default(SIG_DFL)
SIGURG     23    default(SIG_DFL)
SIGUSR1    10    default(SIG_DFL)
SIGUSR2    12    default(SIG_DFL)
SIGVTALRM  26    default(SIG_DFL)
SIGWINCH   28    default(SIG_DFL)
SIGXCPU    24    default(SIG_DFL)
SIGXFSZ    25    ignored(SIG_IGN)
+ /usr/bin/python2 ./tools/display-terminalinfo.py
os.isatty(0) => False
locale.getpreferredencoding() => UTF-8
           pathconf   value
------------------- ---------------------------
       PC_MAX_INPUT   255
        PC_VDISABLE   0
         PC_SYNC_IO   -1
     PC_SOCK_MAXBUF   -1
        PC_NAME_MAX   255
       PC_MAX_CANON   255
         PC_PRIO_IO   -1
PC_CHOWN_RESTRICTED   1
        PC_ASYNC_IO   -1
        PC_NO_TRUNC   1
    PC_FILESIZEBITS   32
        PC_LINK_MAX   127
        PC_PIPE_BUF   4096
        PC_PATH_MAX   4096

stdin is not a typewriter: (25, 'Inappropriate ioctl for device')
++ pwd
+ PYTHONPATH=/builddir/build/BUILD/pexpect-4.0.1
+ /usr/bin/python2 ./tools/display-maxcanon.py
auto-detecting MAX_CANON: 0
```

```
+ /usr/bin/python3 ./tools/display-sighandlers.py
name       value description
---------------------------------
SIGABRT    6     default(SIG_DFL)
SIGALRM    14    default(SIG_DFL)
SIGBUS     7     default(SIG_DFL)
SIGCHLD    17    default(SIG_DFL)
SIGCLD     17    default(SIG_DFL)
SIGCONT    18    default(SIG_DFL)
SIGFPE     8     default(SIG_DFL)
SIGHUP     1     default(SIG_DFL)
SIGILL     4     default(SIG_DFL)
SIGINT     2     <built-in function default_int_handler>
SIGIO      29    default(SIG_DFL)
SIGIOT     6     default(SIG_DFL)
SIGKILL    9     default(SIG_DFL)
SIGPIPE    13    ignored(SIG_IGN)
SIGPOLL    29    default(SIG_DFL)
SIGPROF    27    default(SIG_DFL)
SIGPWR     30    default(SIG_DFL)
SIGQUIT    3     default(SIG_DFL)
SIGRTMAX   64    default(SIG_DFL)
SIGRTMIN   34    default(SIG_DFL)
SIGSEGV    11    default(SIG_DFL)
SIGSTOP    19    default(SIG_DFL)
SIGSYS     31    default(SIG_DFL)
SIGTERM    15    default(SIG_DFL)
SIGTRAP    5     default(SIG_DFL)
SIGTSTP    20    default(SIG_DFL)
SIGTTIN    21    default(SIG_DFL)
SIGTTOU    22    default(SIG_DFL)
SIGURG     23    default(SIG_DFL)
SIGUSR1    10    default(SIG_DFL)
SIGUSR2    12    default(SIG_DFL)
SIGVTALRM  26    default(SIG_DFL)
SIGWINCH   28    default(SIG_DFL)
SIGXCPU    24    default(SIG_DFL)
SIGXFSZ    25    ignored(SIG_IGN)
+ /usr/bin/python3 ./tools/display-terminalinfo.py
os.isatty(0) => False
locale.getpreferredencoding() => UTF-8
             pathconf   value
--------------------- ---------------------------
          PC_PIPE_BUF   4096
         PC_MAX_CANON   255
           PC_PRIO_IO   -1
    PC_ALLOC_SIZE_MIN   4096
  PC_CHOWN_RESTRICTED   1
          PC_NO_TRUNC   1
         PC_MAX_INPUT   255
    PC_REC_XFER_ALIGN   4096
       PC_SYMLINK_MAX   -1
          PC_NAME_MAX   255
          PC_ASYNC_IO   -1
      PC_FILESIZEBITS   32
          PC_LINK_MAX   127
          PC_PATH_MAX   4096
       PC_SOCK_MAXBUF   -1
 PC_REC_MAX_XFER_SIZE   -1
PC_REC_INCR_XFER_SIZE   -1
          PC_VDISABLE   0
           PC_SYNC_IO   -1
 PC_REC_MIN_XFER_SIZE   4096

stdin is not a typewriter: (25, 'Inappropriate ioctl for device')
++ pwd
+ PYTHONPATH=/builddir/build/BUILD/python3-python-pexpect-4.0.1-1.fc24
+ /usr/bin/python3 ./tools/display-maxcanon.py
auto-detecting MAX_CANON: 0
```

**Pull request merged**
