### PR TITLE
Convert @asyncio.coroutine to async def

### PR DESCRIPTION
**Pull request by hroncok**
This is required for Python 3.11+ support.

Fixes https://github.com/pexpect/pexpect/issues/677

### CODE REVIEW

**Comment by mlasch** [comment]
Hi, is there any chance to get this merged soon? This fix would remove quite some warnings from our test system. Also Python 3.11 is just around the corner.

**Comment by Red-M** [comment]
I need to see why the tests for this didn't run but it looks ok.
I'd keep in mind that this doesn't break older versions of python however.

**Comment by Red-M** [comment]
I think #732 supersedes this. Please let me know if this is still required.

**Comment by jreniel** [comment]
> I think #732 supersedes this. Please let me know if this is still required.

Hi, I think it still needs it, I am running into this problem despite having installed the current version of pexpect from git master

**Comment by jreniel** [comment]
@Red-M
Hi  Red, any updates on this? I just migrated a bunch of stuff to pyproject.toml and this issue is still present with Py3.11. However it doesn't look like pexpect yet has a pyproject.toml, which explains why poetry doesn't realize this package currently requires Python < 3.11

**Comment by Red-M** [comment]
Please rebase if you want this, I am pretty sure that other PRs have superseded this one.

**Comment by jreniel** [comment]
@Red-M
Thanks, I will test again with Py 3.11, and hope this has actually been resolved.
Last message on Aug 10, I can definitely say that the pip version wasn't working with async in Py3.11, but I'll have to upgrade my pyproject.toml and rerun my project to actually make sure it works with async in Py3.11.

**Pull request closed without merging**
