### PR TITLE
Freebsd support

### PR DESCRIPTION
**Pull request by jquast**
**major**
- Depends on a new release of ptyprocess for https://github.com/pexpect/ptyprocess/issues/9
- Docfix: FreeBSD's stty(1) manpage is misleading:

  > The system imposes a limit of MAX_INPUT (currently 255) characters in the input queue.

  The real value is ``1920``. Documented it as such.

**minor**
- pass additional arguments in ``tools/teamcity-runtests.sh`` to py.test.
- Catch ValueError in `` tools/display-sighandlers.py``: signals ``SIGRTMAX`` and ``SIGRTMIN`` cannot be inspected on FreeBSD, this is probably intended.

**NOTE**
- the test_maxcanon.py tests had to be disabled for FreeBSD: ``pexpect.sendline('_' * send_bytes)`` causes os.write to **block** indefinitely. I'm going to look into this a bit more to see if there is anything we can do, there.
- Linux failed ``InteractTestCase.test_interact_spawnu_eof`` again.  We really need to track this one down!

### CODE REVIEW

**Comment by jquast** [comment]
ping

**Comment by jquast** [comment]
Added workaround for intermittent EOF in test_interact.py

```
-        p.expect_exact('<eof>')
-        p.expect_exact('Escaped interact')
-        p.expect(pexpect.EOF)
+        # strangely, on travis-ci, sendeof() terminates the subprocess,
+        # it doesn't receive ^D, just immediately throws EOF.
+        idx == p.expect_exact(['<eof>', pexpect.EOF])
+        if idx == 0:
+            p.expect_exact('Escaped interact')
+            p.expect(pexpect.EOF)
```

**Comment by takluyver** [comment]
I think this looks fine, sorry for not reviewing it sooner.

**Comment by jquast** [comment]
thanks!!

**Pull request merged**
