### PR TITLE
Clean up temporary files after UnicodeTests

### PR DESCRIPTION
**Pull request by scfc**

### CODE REVIEW

**Comment by Red-M** [comment]
Has this caused issues?

**Comment by scfc** [comment]
Currently, the test (suite) leaves two temporary files behind after every run.  Is that behaviour intended?  If not, IMNSHO they should be cleaned up after the test has finished.

**Comment by Red-M** [comment]
If you want this merged, please check the other tests as well.

**Comment by scfc** [comment]
I don't know what I can do to resolve those "Expected — Waiting for status to be reported" checks.  My assumption would be that the repository is configured to use Travis CI, and that integration is no longer working.

**Pull request merged**
